language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - 'pypy'
before_install:
  - pip install nose
  - pip install coverage
  - pip install coveralls
install: pip install -r requirements.txt
script: make test
after_script: coveralls
notifications:
  email:
    recipients:
      - romary.dupuis@altarika.com
    on_success: change
    on_failure: always
